
obstacle_range: 2.5 #2.5
raytrace_range: 3.0 #3.0
robot_radius:  0.17 # distance a circular robot should be clear of the obstacle
inflation_radius: 0.09  #0.25
cost_scaling_factor: 2.5 #new #3.0 old
observation_sources: laser_scan_sensor #point_cloud_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
# map_type: costmap #new


#turtlebot3
# obstacle_range: 3.0
# raytrace_range: 3.5

# footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
# #robot_radius: 0.17

# inflation_radius: 1.0
# cost_scaling_factor: 3.0

# map_type: costmap
# observation_sources: scan
# scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
