# DWAPlannerROS:
#   acc_lim_x: 0.1
#   acc_lim_y: 0
#   acc_lim_th: 0.05
#   max_trans_vel: 1.0
#   min_trans_vel: 0.0
#   max_vel_x: 0.5
#   min_vel_x: 0.1
#   max_vel_y: 0
#   min_vel_y: 0
#   max_rot_vel: 0.6
#   min_rot_vel: 0.0

#   yaw_goal_tolerance: 0.7
#   xy_goal_tolerance: 0.2
#   latch_xy_goal_tolerance: false

#   sim_time: 1.5
#   sim_granularity: 0.025
#   vx_samples: 10
#   vy_samples: 0
#   vtheta_samples: 20
#   controller_frequency: 10
#   penalize_negative_x: true

#   path_distance_bias: 1.0
#   goal_distance_bias: 0.8
#   occdist_scale: 0.01
#   forward_point_distance: 0.325
#   stop_time_buffer: 0.2
#   scaling_speed: 1
#   max_scaling_factor: 0.2

#   oscillation_reset_dist: 0.05

#   prune_plan: false  

#   sim_period: 0.1
#   rot_stopped_vel: 0.01
#   trans_stopped_vel: 0.01
# DWAPlannerROS:

# # Robot Configuration Parameters
#   max_vel_x: 0.23
#   min_vel_x: 0.19 #-0.20
#   max_vel_x_backwards: 0 #new

#   max_vel_y: 0.0
#   min_vel_y: 0.0

#   max_rot_vel: 0.7
#   min_rol_vel: 0.27

# # The velocity when robot is moving in a straight line
#   max_vel_trans:  0.26 #0.26
#   min_vel_trans:  0.06

#   max_vel_theta: 1.9 #1.82
#   min_vel_theta: 1.0 #0.9

#   acc_lim_x: 2.0 #2.5
#   acc_lim_y: 0.0
#   acc_lim_th: 2.5 #3.2 

# # Goal Tolerance Parameters
#   xy_goal_tolerance: 0.12  #0.05
#   yaw_goal_tolerance: 2 #0.17
#   latch_xy_goal_tolerance: false

# # Forward Simulation Parameters
#   sim_time: 2.0
#   vx_samples: 20
#   vy_samples: 0
#   vth_samples: 40
#   controller_frequency: 10.0

# # Trajectory Scoring Parameters
#   path_distance_bias: 32.0
#   goal_distance_bias: 20.0
#   occdist_scale: 0.02
#   forward_point_distance: 0.325
#   stop_time_buffer: 0.2
#   scaling_speed: 0.25
#   max_scaling_factor: 0.2

# # Oscillation Prevention Parameters
#   oscillation_reset_dist: 0.05

# # Debugging
#   publish_traj_pc : true
#   publish_cost_grid_pc: true

#########################################################################

#turtlebot3
DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.26
  min_vel_x: 0 #-0.26 

  max_vel_y: 0.0
  min_vel_y: 0.0

  # max_vel_x_backwards: 0 

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.26
  min_vel_trans:  0.15

  max_vel_theta: 1.82
  min_vel_theta: 0.9

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 1.0
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 2.0
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
